### ISSUE TITLE
contrib/plugins/apache/apache_memmory syntax error in Ubuntu 18.04

### ISSUE THREAD

**Issue by bolduz** [munin-monitoring/contrib#1066]
Hello,
running the following command gives an error, caused by an improper escaping of grep parameters:

```
# munin-run apache_memmory --debug
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Processing plugin configuration from /etc/munin/plugin-conf.d/mysql
# Setting /rgid/ruid/ to /119/65534/
# Setting /egid/euid/ to /119 119/65534/
# Setting up environment
# About to run '/etc/munin/plugins/apache_memmory'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
expr: syntax error
servers.value
```

Line 61 of the plugin should be modified from:

```sh
VAL1=`ps auxf | grep ${PROCS} | grep ^${USR} | grep -v grep | wc -l`
```

to the following:

```sh
VAL1=`ps auxf | grep "${PROCS}" | grep "^${USR}" | grep -v grep | wc -l`
```

Line 63 of the plugin should be modified from

```sh
VAL2=`ps auxf | grep ${PROCS} | grep ^${USR} | grep -v grep | awk '{s+=$6} END {print s}'`
```

to the following:

```sh
VAL2=`ps auxf | grep "${PROCS}" | grep "^${USR}" | grep -v grep | awk '{s+=$6} END {print s}'`
```

Thank you.

**Comment by sumpfralle** [comment]
Thank you for reporting this!

I took the liberty to give the plugin an overhaul. This includes a rename (fixing the spelling mistake in the name) and changing the output scale to the base SI unit (bytes instead of kBytes).

Please report back, if you encounter any issues.

PS: I just read your other two bug reports for similar plugins. What a mess :(

(I will take a look at these too ...)
