### ISSUE TITLE
dnsresponse_: works, but with errors

### ISSUE THREAD

**Issue by quotengrote** [munin-monitoring/contrib#1288]
Hi, the [dnsreponse_](https://github.com/munin-monitoring/contrib/blob/master/plugins/network/dns/dnsresponse_) Plugins work, but i outputs an error.

```shell
root@dnsmasq:/etc/munin/plugins# sudo munin-run dnsresponse_mgrote
unresolvable name: mgrote at /etc/munin/plugins/dnsresponse_mgrote line 123.
avg.value 0.04845
median.value 0.042
stddev.value 0.0175740575849745

````

But i don't see it, and it works as designed...

**Comment by sumpfralle** [comment]
According to the plugin source, the *suffix* of the plugin filename is interpreted as the nameserver.
Thus the plugin tries to query the nameserver `grote`. This fails and thus it probably uses your local default nameserver.

In order to avoid problems, you should use the IP of the nameserver (e.g. `dnsresponse_1.2.3.4`).

Feel free to propose improvements for the `dnsresponse_` documentation. It clearly lacks this crucial piece of information.
