### ISSUE TITLE
kvm_mem reporting max memory, not current

### ISSUE THREAD

**Issue by rkarlsba** [munin-monitoring/contrib#702]
Seems kvm_mem reports 'maximum allocation', not 'current allocation' when listing VMs, and thus giving inaccurate data (I usually set maximum to a likely max for a new vm, and just allocate when needed). Using virsh dommemstat <domname> would be accurate, although it would need sudo setup

**Comment by sumpfralle** [comment]
Personally I do expect, that virtualization plugins would tell me the amount of *designated* instead of *used* memory, since *being in use* is a state that can cause misunderstandings (buffer, cache, ...).

Probably a new plugin (or a confguration setting) could be added in order to track the amount returned by dommemstat.

`sudo` would not be a real issue, since plugins can be configured to run as root.
