### ISSUE TITLE
Asterisk: all values set to "U"

### ISSUE THREAD

**Issue by thijsvdc** [munin-monitoring/contrib#887]
Hi,

I'm having an issue with the asterisk plugin. This is the complete output:

cli# munin-run asterisk
Use of uninitialized value $channels_response in pattern match (m//) at /etc/munin/plugins/asterisk line 254.

multigraph asterisk_channels
total.value U
Zap.value U
IAX2.value U
SIP.value U

multigraph asterisk_voicemail
total.value U

multigraph asterisk_meetme
users.value U
conferences.value U

multigraph asterisk_codecs
gsm.value U
ulaw.value U
alaw.value U
other.value U
unknown.valeu U

Thanks
Thijs

**Comment by sumpfralle** [comment]
Where exactly does this plugin come from? (there are multiple asterisk plugins)
Which version of munin do you use?
Did you configure the plugin (username, password, ...)?
Did it work before?

**Comment by sumpfralle** [comment]
Thank you for updating the issue!

The warning (`Use of uninitialized value $channels_response in pattern match (m//) at /etc/munin/plugins/asterisk line 254.`) seems to be caused by a parsing problem with the output of `core show channels` (via the telnet interface).
Could you share the output of that command with us?
